pipeline {
    agent any
    environment {
        MAVEN_OPTS = '-Xmx1024m -B -q -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
    }

    stages {

        stage('Info') {
            agent any
            steps {
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
            }
        }

        stage('Lint') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                    args '-u 0:0' // ejecuta como root dentro del contenedor
                }
            }
            steps {
                echo "Running Lint (fast feedback)..."
                // Usamos Maven Checkstyle para lint de Java
                sh 'mvn clean verify -Dcheckstyle.failOnViolation=true || true'
                // Guardamos los reportes para Jenkins
                archiveArtifacts artifacts: 'target/checkstyle-result.xml', allowEmptyArchive: true
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                    args '-u 0:0'
                }
            }
            steps {
                echo "Running unit tests..."
                // Maven Surefire plugin para tests
                sh 'mvn test || true'
                junit 'target/surefire-reports/*.xml'
            }
        }

        stage('Package') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                    args '-u 0:0'
                }
            }
            steps {
                echo "Building JAR..."
                sh 'mvn package'
                archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: false
            }
        }

    } // stages
}
