// ---------- Función reutilizable ----------
def runInDocker(String image, Closure body) {
    docker.image(image).inside('-u 0:0') {
        body()
    }
}
pipeline {
    agent any
    environment {
        MAVEN_OPTS = '-Xmx1024m'
    }
    stages {
        stage('Info') {
            steps {
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
            }
        }
        stage('Lint') {
            steps {
                echo "Running Lint (Checkstyle only)..."
                runInDocker('maven:3.8.6-openjdk-11-slim') {
                    sh 'mvn checkstyle:check -q -B || true'
                }
            }
        }
        stage('Test') {
            steps {
                echo "Running unit tests..."
                runInDocker('maven:3.8.6-openjdk-11-slim') {
                    sh 'mvn test -q -B'
                }
                junit 'target/surefire-reports/*.xml'
            }
        }
        stage('Build image') {
            steps {
                echo "Building Docker image..."
                script {
                    def version
                    runInDocker('maven:3.8.6-openjdk-11-slim') {
                        version = sh(script: 'mvn help:evaluate -Dexpression=project.version -q -DforceStdout', returnStdout: true).trim()
                    }
                    docker.build("java-app:${env.BUILD_NUMBER}", "--build-arg VERSION=${version} -f devops/Dockerfile .")
                    echo "Image built: java-app:${env.BUILD_NUMBER}"
                }
            }
        }
        stage('CD') {
            steps {
                script {
                    try {
                        sh 'docker compose -f docker-compose.yml up -d java_app'
                        sleep 5
                        sh 'curl -f http://localhost:8084/hello'
                    } finally {
                        sh 'docker compose -f docker-compose.yml down --volumes'
                    }
                }
            }
        }
    }
}
