// ------------------------
// Función reutilizable
// ------------------------
def runInDocker(String image, Closure body) {
    docker.image(image).inside('-u 0:0') {
        body()
    }
}

// ------------------------
// Pipeline
// ------------------------
pipeline {
    agent any
    environment {
        MAVEN_OPTS = '-Xmx1024m'
    }

    stages {

        stage('Info') {
            steps {
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
            }
        }

        stage('Lint') {
            steps {
                echo "Running Lint (fast feedback)..."
                runInDocker('maven:3.8.6-openjdk-11-slim') {
                    sh 'mvn clean verify -q -B -Dcheckstyle.failOnViolation=true || true'
                    archiveArtifacts artifacts: 'target/checkstyle-result.xml', allowEmptyArchive: true
                }
            }
        }

        stage('Test') {
            steps {
                echo "Running unit tests..."
                runInDocker('maven:3.8.6-openjdk-11-slim') {
                    sh 'mvn test -q -B || true'
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Package') {
            steps {
                echo "Building JAR..."
                runInDocker('maven:3.8.6-openjdk-11-slim') {
                    sh 'mvn package -q -B'
                    archiveArtifacts artifacts: 'target/*.jar', allowEmptyArchive: false
                }
            }
        }

    } // stages
}
